<a href="https://colab.research.google.com/github/neerukondaramalakshmi2005-dotcom/Data-Analysis-/blob/main/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd
print("pandas imported")

pandas imported


In [ ]:
# Creating Series pd
Data = [ 2,4,6,8]
s = pd.Series(Data)
print(s)

0    2
1    4
2    6
3    8
dtype: int64


In [ ]:
Data = [1,2,3,4,5]
i=['a','b','c','d','e']
s = pd.Series(Data,index =i)
print(s)

#updating
s['a'] = 10
print(s)
s['b'] =50
print(s)

#inserting new data(directly,concat)
s["f"] = 80
print(s)

# remove (drop method)
s = s.drop("a")
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    10
b     2
c     3
d     4
e     5
dtype: int64
a    10
b    50
c     3
d     4
e     5
dtype: int64
a    10
b    50
c     3
d     4
e     5
f    80
dtype: int64
b    50
c     3
d     4
e     5
f    80
dtype: int64


In [ ]:
# Creating a Series from a Dictionary
s2 = pd.Series({'x': 100, 'y': 200, 'z': 300})
print(s2)
# Accessing elements
print(s2[0])
print(s2[0:2])
print(s2[1:])
print(s2[:2])
print(s2[2])
print(s2[2:3])


x    100
y    200
z    300
dtype: int64
100
x    100
y    200
dtype: int64
y    200
z    300
dtype: int64
x    100
y    200
dtype: int64
300
z    300
dtype: int64


/tmp/ipykernel_3580/2231854243.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[0])
/tmp/ipykernel_3580/2231854243.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[2])


In [ ]:

import pandas as pd
Students_id = [ 101, 102, 103, 104, 105]
marks = [ 78, 85,  92, 67, 88]
s =pd.Series(Students_id , marks)
print(s)

78    101
85    102
92    103
67    104
88    105
dtype: int64


In [ ]:
import pandas as pd
product_id = [101, 102,  103, 104, 105]
price = [500,750,1200,900,1500]
s =pd.Series(product_id,price)
print(s)

500     101
750     102
1200    103
900     104
1500    105
dtype: int64


In [ ]:
# Dictonary of series
import pandas as pd
data = {'a':100,'b':200,'c':300}
s = pd.Series(data)
print(s)

a    100
b    200
c    300
dtype: int64


In [ ]:

#viewing Data Frames
import pandas as pd
s = pd.Series(
    [5000, 7000, 9000, 8000, 9000],

    index=["Monday", "Tuesday" , "Wednesday", "Thursday","Friday"]
)
print(s)
# (s.head) it is first 5 rows  to create and updating only
print(s.head)
print(s.head(5))
#s.tail() it is last 5 rows  values or rows
print(s.tail)
print(s.tail(3))
#len(s) it is used for rows and columns
print(len(s))
#(s.shape) it is used for rows and columns
print(s.shape)
#(s.index) it is used for rows and columns
print(s.index)
#(s.values) it is used for rows and columns
print(s.values)

Monday       5000
Tuesday      7000
Wednesday    9000
Thursday     8000
Friday       9000
dtype: int64
<bound method NDFrame.head of Monday       5000
Tuesday      7000
Wednesday    9000
Thursday     8000
Friday       9000
dtype: int64>
Monday       5000
Tuesday      7000
Wednesday    9000
Thursday     8000
Friday       9000
dtype: int64
<bound method NDFrame.tail of Monday       5000
Tuesday      7000
Wednesday    9000
Thursday     8000
Friday       9000
dtype: int64>
Wednesday    9000
Thursday     8000
Friday       9000
dtype: int64
5
(5,)
Index(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], dtype='object')
[5000 7000 9000 8000 9000]


In [ ]:
#selecting/filtering
# selecting means choose the specific rows and columns.
# filtering means selecting rows is based ona condition.
# uses of the &->And, |->OR, ==->Equalto ,>-> Greaterthan, < --->lessthan, !=--> Notequal
import pandas as pd
s = pd.Series(
    [5000, 7000, 9000, 8000, 9000],

    index=["Monday", "Tuesday" , "Wednesday", "Thursday","Friday"]
)
print(s)
print(s["Monday"])
print(s[["Friday", "Wednesday"]])
#(s. iloc) No index (position based on the select data using the integer position or index)
s.iloc[0:3]
# (s.loc) it is label -based on user name and
s.loc["Wednesday"]
s.loc["Thursday"]
s.loc[s == 8000]
s.iloc[0:3]
# filtering with using condition (select a range)
s[s>7000]
#To get only value to less than
s[s<9000]
s[s!=7000]
#To get only value to greater than
s[s>7000]



Monday       5000
Tuesday      7000
Wednesday    9000
Thursday     8000
Friday       9000
dtype: int64
5000
Friday       9000
Wednesday    9000
dtype: int64


,0
Wednesday,9000
Thursday,8000
Friday,9000


In [ ]:
#  Cleaning Data Frames
# there are types of creating Data types ,1. missing values,2.incorrect values ,
#3. Duplicate data ,4. invalid Data
# But  it is only using the only missing values.......
# missing values of data [it represesent the NaN (NOT A NUMBER)]
# In this method is some methods are available.
# isna(), isna().sum(), dropna(), fillna()

import pandas as pd
s = pd.Series([5000, 6000, 70000, None, 9000, None])
print(s)
# s.isna().sum() count missing values
print(s.isna().sum())
# s.isna()find the missing values
print(s.isna())
# s.fillna() it is fill the missing values
print(s.fillna(0))
# s.dropna() it is remove the missing values
print(s.dropna())
#replace method it is represented by the s=s.replace(5000,55000)
s = s.replace(5000, 55000)
print(s)

0     5000.0
1     6000.0
2    70000.0
3        NaN
4     9000.0
5        NaN
dtype: float64
2
0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool
0     5000.0
1     6000.0
2    70000.0
3        0.0
4     9000.0
5        0.0
dtype: float64
0     5000.0
1     6000.0
2    70000.0
4     9000.0
dtype: float64
0    55000.0
1     6000.0
2    70000.0
3        NaN
4     9000.0
5        NaN
dtype: float64


In [ ]:
# creating Data  Frame
# from a Dictonary of lists
# From a lists and tuples
#dictonary is always unique of keys , it represented by the
#colon : before is keys
# and colon opposite is values.

import pandas as pd
data = {'Name' : ['Rama','Prashu','mani'],
        'Age': [23,34,56],
        'Score':[340,980,340]}

df = pd.DataFrame(data)
print(df)




     Name  Age  Score
0    Rama   23    340
1  Prashu   34    980
2    mani   56    340


In [ ]:
# creating a set (df_from_set)
import pandas as pd
my_set ={100,200,400,300}
df_from_set = pd.DataFrame(
    list(my_set),
    #column = [ 'values']
)
print(df_from_set)

     0
0  200
1  100
2  400
3  300


In [ ]:
 # converting a series into DataFrame
 # A series contain only one dimension, while a Data frame contain multiple,
 #colmns to_frame() one column Data Frame
 # df = s.to_Frame()
  # single series into convert  to data frame is called s.to_frame
  # multiple colums to convert  series inti data frames
  #is called df = pd.DataFrame(d)

import pandas as pd
s = pd.Series(
    [1,2,3,4],
    name='Numbers1'
)
s2 = pd.Series(
    [9,6,7,8],
    name='Numbers2'
)
s3 = pd.Series(
    [34,56,78,94],
    name='Numbers3'
)
df = pd.concat([s, s2, s3], axis=1)

print(df)

   Numbers1  Numbers2  Numbers3
0         1         9        34
1         2         6        56
2         3         7        78
3         4         8        94


In [ ]:
import pandas as pd
s = pd.Series(
    [1,2,3,4],
    name='Numbers1'
)
s2 =pd.Series([9,6,7,8])
s3 =pd.Series([12, 13, 14,15])
df = s.to_frame()
print(df)

   Numbers1
0         1
1         2
2         3
3         4


In [ ]:
import pandas as pd
s = pd.Series(
    [1,2,3,4],
    name='Numbers1'
)
s2 =pd.Series([9,6,7,8])
s3 =pd.Series([12, 13, 14,15])
df = s.to_frame()
d ={
    "name" :s,
    "age" :s2,
    "marks" :s3
}
df = pd.DataFrame(d)
print(df)

   name  age  marks
0     1    9     12
1     2    6     13
2     3    7     14
3     4    8     15


In [ ]:
import pandas as pd
s1 = pd.Series([100, 200, 300])
s2 = pd.Series([400, 500, 600])
print(s1)
print(s2)
r = pd.concat([s1,s2],ignore_index=True)
print(r)

0    100
1    200
2    300
dtype: int64
0    400
1    500
2    600
dtype: int64
0    100
1    200
2    300
3    400
4    500
5    600
dtype: int64


In [ ]:
import pandas as pd
data = {
    "Name": ["Rama", "Prashu", "Mani", "Ammu", "Meena"],
    "age": [ 22, 34, None, 56, None],
    "City": ["Hyderabad", "Vishakapatnam", "Vijawada", None,"Mumbai"],
    "Salary": [38000, 56000, 34000, None, 23000]
}
i = [101,102,103,104,105]
df = pd.DataFrame(data,index = i)
print(df)
df.iloc[0:3]
# loc
df.loc[103:104]


       Name   age           City   Salary
101    Rama  22.0      Hyderabad  38000.0
102  Prashu  34.0  Vishakapatnam  56000.0
103    Mani   NaN       Vijawada  34000.0
104    Ammu  56.0           None      NaN
105   Meena   NaN         Mumbai  23000.0


,Name,age,City,Salary
103,Mani,NaN,Vijawada,34000.0
104,Ammu,56.0,None,NaN


In [ ]:
import pandas as pd
s = pd.Series(
    [5000, 7000, 9000, 8000, 9000],

    index=["Monday", "Tuesday" , "Wednesday", "Thursday","Friday"]
)
print(s)
s.iloc[0:3]
s.max()
s.min()
s.mean()
s.median()
s.sum()
s.count()
s.std()
s.max()
s.min()


Monday       5000
Tuesday      7000
Wednesday    9000
Thursday     8000
Friday       9000
dtype: int64


5000

In [ ]:
# Rename the columns
#   if we have to vhange the column it will  change in this format  to using
#the multiple colums are using   in df.rename()
import pandas as pd
s = pd.Series(
    [1,2,3,4],
    name='Numbers1'
)
df = s.to_frame()
df.columns = ['Digits']
print(df)


   Digits
0       1
1       2
2       3
3       4


In [ ]:
d = {"A":[1,2],
     "b":[3,4]}
df=pd.DataFrame(d)
print(df)

   A  b
0  1  3
1  2  4


In [ ]:
# Rename the columns
#   if we have to change the column it will  change in this format  to using
#the multiple colums are using   in df.rename()
# to add inplace is called True value
# to remove the inplace value
import pandas as pd
df.rename(
    columns={
        'A' : 'Alpha',
        'b' : 'Beta'
    },
    inplace = True

)
print(df)

              0
Monday     5000
Tuesday    7000
Wednesday  9000
Thursday   8000
Friday     9000


In [ ]:
# to remove the inplace value
import pandas as pd
df.rename(
    columns={
        'A' : 'Alpha',
        'B' : 'Beta'
    },
)
print(df)
print(df)

              0
Monday     5000
Tuesday    7000
Wednesday  9000
Thursday   8000
Friday     9000
              0
Monday     5000
Tuesday    7000
Wednesday  9000
Thursday   8000
Friday     9000


In [ ]:
import pandas as pd
s = pd.Series(
    [5000, 7000, 9000, 8000, 9000],

    index=["Monday", "Tuesday" , "Wednesday", "Thursday","Friday"]
)
df = pd.DataFrame(s)
df.info()
df.describe()
df.info()


<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Monday to Friday
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int64
dtypes: int64(1)
memory usage: 80.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Monday to Friday
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int64
dtypes: int64(1)
memory usage: 80.0+ bytes


In [ ]:
import pandas as pd
s = pd.Series(
    [5000, 7000, 9000, 8000, 9000],

    index=["Monday", "Tuesday" , "Wednesday", "Thursday","Friday"]
)
df = pd.DataFrame(s)
df.describe()



,0
count,5.000000
mean,7600.000000
std,1673.320053
min,5000.000000
25%,7000.000000
50%,8000.000000
75%,9000.000000
max,9000.000000


In [ ]:
import pandas as pd
Data = {
    "Name": ["Rama", "Prashu", "Mani", "Ammu", "Meena"],
    "age": [ 22, 34, None, 56, None],
    "City": ["Hyderabad", "Vishakapatnam", "Vijawada", None,"Mumbai"],
    "Salary": [38000, 56000, 34000, None, 23000]
}
df = pd.DataFrame(Data)
df[["Name","age"]]



,Name,age
0,Rama,22.0
1,Prashu,34.0
2,Mani,NaN
3,Ammu,56.0
4,Meena,NaN


In [ ]:

#selecting
import pandas as pd
data = {
    "Name": ["Rama", "Prashu", "Mani", "Ammu", "Meena"],
    "age": [ 22, 34, None, 56, None],
    "City": ["Hyderabad", "Vishakapatnam", "Vijawada", None,"Mumbai"],
    "Salary": [38000, 56000, 34000, None, 23000]
}
i = [101,102,103,104,105]
df = pd.DataFrame(data,index = i)
print(df)
df[['Name','age']]

       Name   age           City   Salary
101    Rama  22.0      Hyderabad  38000.0
102  Prashu  34.0  Vishakapatnam  56000.0
103    Mani   NaN       Vijawada  34000.0
104    Ammu  56.0           None      NaN
105   Meena   NaN         Mumbai  23000.0


,Name,age
101,Rama,22.0
102,Prashu,34.0
103,Mani,NaN
104,Ammu,56.0
105,Meena,NaN


In [ ]:
import pandas as pd
data = {
    "Name": ["Rama", "Prashu", "Mani", "Ammu", "Meena"],
    "age": [ 22, 34, None, 56, None],
    "City": ["Hyderabad", "Vishakapatnam", "Vijawada", None,"Mumbai"],
    "Salary": [38000, 56000, 34000, None, 23000]
}
i = [101,102,103,104,105]
df = pd.DataFrame(data,index = i)
print(df)
df[['Name','age']]
df.iloc[4]
df.iloc[0:3]

       Name   age           City   Salary
101    Rama  22.0      Hyderabad  38000.0
102  Prashu  34.0  Vishakapatnam  56000.0
103    Mani   NaN       Vijawada  34000.0
104    Ammu  56.0           None      NaN
105   Meena   NaN         Mumbai  23000.0


,Name,age,City,Salary
101,Rama,22.0,Hyderabad,38000.0
102,Prashu,34.0,Vishakapatnam,56000.0
103,Mani,NaN,Vijawada,34000.0


In [ ]:
import pandas as pd
data = {
    "Name": ["Rama", "Prashu", "Mani", "Ammu", "Meena"],
    "age": [ 22, 34, None, 56, None],
    "City": ["Hyderabad", "Vishakapatnam", "Vijawada", None,"Mumbai"],
    "Salary": [38000, 56000, 34000, None, 23000]
}
i = [101,102,103,104,105]
df = pd.DataFrame(data,index = i)
print(df)
df[['Name','age']]
df.iloc[4]
df.iloc[0:3]

       Name   age           City   Salary
101    Rama  22.0      Hyderabad  38000.0
102  Prashu  34.0  Vishakapatnam  56000.0
103    Mani   NaN       Vijawada  34000.0
104    Ammu  56.0           None      NaN
105   Meena   NaN         Mumbai  23000.0


,Name,age,City,Salary
101,Rama,22.0,Hyderabad,38000.0
102,Prashu,34.0,Vishakapatnam,56000.0
103,Mani,NaN,Vijawada,34000.0


In [ ]:

#filtering
import pandas as pd
data = {
    "Name": ["Rama", "Prashu", "Mani", "Ammu", "Meena"],
    "age": [ 22, 34, None, 56, None],
    "City": ["Hyderabad", "Vishakapatnam", "Vijawada", None,"Mumbai"],
    "Salary": [38000, 56000, 47000, None, 23000]
}
i = [101,102,103,104,105]
df = pd.DataFrame(data,index = i)
print(df)
d = df[df["age"] >22]
print(d)
b = df["age"] >22
print(b)
f = df[df["Salary"] >23000]
print(f)

g= df[df["City"] =="Hyderabad"]
print(g)




       Name   age           City   Salary
101    Rama  22.0      Hyderabad  38000.0
102  Prashu  34.0  Vishakapatnam  56000.0
103    Mani   NaN       Vijawada  47000.0
104    Ammu  56.0           None      NaN
105   Meena   NaN         Mumbai  23000.0
       Name   age           City   Salary
102  Prashu  34.0  Vishakapatnam  56000.0
104    Ammu  56.0           None      NaN
101    False
102     True
103    False
104     True
105    False
Name: age, dtype: bool
       Name   age           City   Salary
101    Rama  22.0      Hyderabad  38000.0
102  Prashu  34.0  Vishakapatnam  56000.0
103    Mani   NaN       Vijawada  47000.0
     Name   age       City   Salary
101  Rama  22.0  Hyderabad  38000.0


In [ ]:
#filtering
import pandas as pd
data = {
    "Name": ["Rama", "Prashu", "Mani", "Ammu", "Meena"],
    "age": [ 22, 34, None, 56, None],
    "City": ["Hyderabad", "Vishakapatnam", "Mumbai", None,"Mumbai"],
    "Salary": [38000, 56000, 47000, None, 2300000]
}
i = [101,102,103,104,105]
df = pd.DataFrame(data,index = i)
print(df)
r =df[
    (df["Salary"] >38000)|
    (df["City"] == "Mumbai")
]
print(r)

       Name   age           City     Salary
101    Rama  22.0      Hyderabad    38000.0
102  Prashu  34.0  Vishakapatnam    56000.0
103    Mani   NaN         Mumbai    47000.0
104    Ammu  56.0           None        NaN
105   Meena   NaN         Mumbai  2300000.0
       Name   age           City     Salary
102  Prashu  34.0  Vishakapatnam    56000.0
103    Mani   NaN         Mumbai    47000.0
105   Meena   NaN         Mumbai  2300000.0


In [ ]:
#cleaning Data
#missing Values
import pandas as pd
Data = {
    "A" : [3,5],
    "B" : [4,5]
    }

df = pd.DataFrame(Data)
print(df.isna())
print(df.dropna())


       A      B
0  False  False
1  False  False
   A  B
0  3  4
1  5  5


In [ ]:
import pandas as pd
Data = {
    "Data" : [5000, 7000, 9000, 8000, 9000],

   "Index" : ["Monday", "Tuesday" , "Wednesday", "Thursday","Friday"]
}
df = pd.DataFrame(Data)
print(df.isna())




    Data  Index
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False


In [ ]:
import pandas as pd
Data = {
    "Data" : [5000, 7000, 9000, 8000, 9000],

   "Index" : ["Monday", "Tuesday" , "Wednesday", "Thursday","Friday"]
}
df = pd.DataFrame(Data)
df = df.set_index("Index")
print(df.drop("Monday"))


           Data
Index          
Tuesday    7000
Wednesday  9000
Thursday   8000
Friday     9000


In [ ]:
import pandas as pd
Data = {
    "Data" : [5000, 7000, None ,8000, None, 9000],

   "Index" : ["Monday", "Tuesday" , "Wednesday", "Thursday","Friday", "Sunday"]
}
df = pd.DataFrame(Data)
print(df.fillna(4000))


     Data      Index
0  5000.0     Monday
1  7000.0    Tuesday
2  4000.0  Wednesday
3  8000.0   Thursday
4  4000.0     Friday
5  9000.0     Sunday


In [ ]:
import pandas as pd
Data = {
    "Data" : [5000, 7000, None ,8000, None, 9000],

   "Index" : ["Monday", "Tuesday" , "Wednesday", "Thursday","Friday", "Sunday"]
}
df = pd.DataFrame(Data)
print(df.isna().sum())


Data     2
Index    0
dtype: int64


In [ ]:
import pandas as pd
Data = {
    "Data" : [5000, 7000, None ,8000, None, 9000],

   "Index" : ["Monday", "Tuesday" , "Wednesday", "Thursday","Friday", "Sunday"]
}
df = pd.DataFrame(Data)
print(s.isna().sum())
print(df.dropna())

0
     Data     Index
0  5000.0    Monday
1  7000.0   Tuesday
3  8000.0  Thursday
5  9000.0    Sunday


In [ ]:
import pandas as pd
Data = {
    "Data" : [5000, 7000, None ,8000, None, 9000],

   "Index" : ["Monday", "Tuesday" , "Wednesday", "Thursday","Friday", "Sunday"]
}
df = pd.DataFrame(Data)
print(df.dropna(axis=1))

       Index
0     Monday
1    Tuesday
2  Wednesday
3   Thursday
4     Friday
5     Sunday


In [ ]:
import pandas as pd
Data = {
    "Data" : [5000, 7000, None ,8000, None, 9000],

   "Index" : ["Monday", "Tuesday" , "Wednesday", "Thursday","Friday", "Sunday"]
}
df = pd.DataFrame(Data)
print(df.dropna(axis=0))

     Data     Index
0  5000.0    Monday
1  7000.0   Tuesday
3  8000.0  Thursday
5  9000.0    Sunday


In [ ]:
import pandas as pd
Data = {
    "Data" : [5000, 7000, None ,8000, None, 9000],

   "Index" : ["Monday", "Tuesday" , "Wednesday", None,  "Thursday","Friday", "Sunday"]
}
df = pd.DataFrame(Data)
print(df.dropna(how='all'))
print(df)

     Data      Index
0  5000.0     Monday
1  7000.0    Tuesday
2     NaN  Wednesday
3  8000.0   Thursday
4     NaN     Friday
5  9000.0     Sunday
     Data      Index
0  5000.0     Monday
1  7000.0    Tuesday
2     NaN  Wednesday
3  8000.0   Thursday
4     NaN     Friday
5  9000.0     Sunday


In [ ]:
df = pd.DataFrame(Data)
print(df.dropna(axis=0,inplace=True))
print(df)

None
     Data     Index
0  5000.0    Monday
1  7000.0   Tuesday
3  8000.0  Thursday
5  9000.0    Sunday


In [ ]:
df = pd.DataFrame(Data)
print(df.fillna({
    'Data' : 0,
    'Index': 'Vizag'

}))


     Data      Index
0  5000.0     Monday
1  7000.0    Tuesday
2     0.0  Wednesday
3  8000.0   Thursday
4     0.0     Friday
5  9000.0     Sunday


In [ ]:
import pandas as pd
Data = {
    "Data" : [5000, 7000, None ,8000, None, 9000],

   "Index" : ["Monday", "Tuesday" , "Wednesday", None,  "Thursday","Friday"]
}

df = pd.DataFrame(Data)
print(df['Data'] == df['Data'].fillna(df['Data'].mean()))



0     True
1     True
2    False
3     True
4    False
5     True
Name: Data, dtype: bool


In [ ]:
import pandas as pd
emp_details = {
    "EmpiD":[101,102,103,104,105],
    "Name": ["Rama", "Prashu", "Mani", "Ammu", "Meena"],
    "age": [ 22, 34, None, 56, None],
    "City": ["Hyderabad", "Vishakapatnam", "Hyderabad", None,"Mumbai"],
    "Salary": [38000, 56000, 34000, None, 23000],
    "Experience":[23,25,30,None,45]
}
df = pd.DataFrame(emp_details)
print(df['Experience'] == df['Experience'].fillna(df['Experience'].mean()))
print(df['age'] == df['age'].fillna(df['age'].median()))


0     True
1     True
2     True
3    False
4     True
Name: Experience, dtype: bool
0     True
1     True
2    False
3     True
4    False
Name: age, dtype: bool


In [ ]:
#Aggreations
#Groupy() method
import pandas as pd
emp_details = {
    "EmpiD":[101,102,103,104,105],
    "Name": ["Rama", "Prashu", "Mani", "Ammu", "Meena"],
    "age": [ 22, 34, None, 56, None,],
    "City": ["Hyderabad", "Vishakapatnam", "Hyderabad", None,"Mumbai"],
    "Salary": [38000, 56000, 34000, None, 23000],
    "Experience":[23,25,30,None,45]
}
df = pd.DataFrame(emp_details)
print(df)
df.groupby("City")["age"].mean()
df.groupby("City")["age"].max()
df.groupby("City")["age"].min()
df.groupby("Experience")["Salary"].sum()
df.groupby("City")["Salary"].sum()









   EmpiD    Name   age           City   Salary  Experience
0    101    Rama  22.0      Hyderabad  38000.0        23.0
1    102  Prashu  34.0  Vishakapatnam  56000.0        25.0
2    103    Mani   NaN      Hyderabad  34000.0        30.0
3    104    Ammu  56.0           None      NaN         NaN
4    105   Meena   NaN         Mumbai  23000.0        45.0


,Salary
City,
Hyderabad,72000.0
Mumbai,23000.0
Vishakapatnam,56000.0


In [ ]:
#



import pandas as pd
emp_details = {
    "EmpiD":[101,102,103,104,105],
    "Name": ["Rama", "Prashu", "Mani", "Ammu", "Meena"],
    "age": [ 22, 34, None, 56, None],
    "City": ["Hyderabad", "Vishakapatnam", "Hyderabad", None,"Mumbai"],
    "Salary": [38000, 56000, 34000, None, 23000],
    "Experience":[23,25,30,None,45],
    "age": [ 22, 34, None, 56, None],
    "City": ["Hyderabad", "Vishakapatnam", "Hyderabad", None,"Mumbai"]
}
df = pd.DataFrame(emp_details)
df.rename(columns={"EmpiD":"employee" })
df['salary']=[1000,2000,3000,4000,None]
print(df)
df['age']=df['age']+1
print(df)
df['Bonus'] = df['salary']*0.20
print(df)
df.drop('salary',axis=1,inplace=True)
print(df)
df.drop(columns=['age','City'],inplace=True)
print(df)
df.loc[len(df)] = [106,"Mamu",36000, 55,300]
print(df)
df.drop(2,axis=0,inplace=True)
print(df)


   EmpiD    Name   age           City   Salary  Experience  salary
0    101    Rama  22.0      Hyderabad  38000.0        23.0  1000.0
1    102  Prashu  34.0  Vishakapatnam  56000.0        25.0  2000.0
2    103    Mani   NaN      Hyderabad  34000.0        30.0  3000.0
3    104    Ammu  56.0           None      NaN         NaN  4000.0
4    105   Meena   NaN         Mumbai  23000.0        45.0     NaN
   EmpiD    Name   age           City   Salary  Experience  salary
0    101    Rama  23.0      Hyderabad  38000.0        23.0  1000.0
1    102  Prashu  35.0  Vishakapatnam  56000.0        25.0  2000.0
2    103    Mani   NaN      Hyderabad  34000.0        30.0  3000.0
3    104    Ammu  57.0           None      NaN         NaN  4000.0
4    105   Meena   NaN         Mumbai  23000.0        45.0     NaN
   EmpiD    Name   age           City   Salary  Experience  salary  Bonus
0    101    Rama  23.0      Hyderabad  38000.0        23.0  1000.0  200.0
1    102  Prashu  35.0  Vishakapatnam  56000.0  

In [ ]:
emp_details={
    "empID":[101,102,103,104,101],
    "city":["hyd","chennai","bangalore",None,"hyd"],
    "exp":[None,4,3,5,2],
    "age":[25,30,None,35,25]
}
df=pd.DataFrame(emp_details)
print(df.fillna({'city':'unknown'}))
print(df.fillna({'exp':'0'}))
print(df['age']==df['age'].fillna(df['age'].median()))
print(df.rename(columns={'empID':'employee_id'}))
print(df)
print(df.rename(columns={'empID':'employee_id'},inplace=True))
print(df)
df['salary']=[1000,2000,3000,4000,None]
print(df)
df['age']=df['age']+1
print(df)

   empID       city  exp   age
0    101        hyd  NaN  25.0
1    102    chennai  4.0  30.0
2    103  bangalore  3.0   NaN
3    104    unknown  5.0  35.0
4    101        hyd  2.0  25.0
   empID       city  exp   age
0    101        hyd    0  25.0
1    102    chennai  4.0  30.0
2    103  bangalore  3.0   NaN
3    104       None  5.0  35.0
4    101        hyd  2.0  25.0
0     True
1     True
2    False
3     True
4     True
Name: age, dtype: bool
   employee_id       city  exp   age
0          101        hyd  NaN  25.0
1          102    chennai  4.0  30.0
2          103  bangalore  3.0   NaN
3          104       None  5.0  35.0
4          101        hyd  2.0  25.0
   empID       city  exp   age
0    101        hyd  NaN  25.0
1    102    chennai  4.0  30.0
2    103  bangalore  3.0   NaN
3    104       None  5.0  35.0
4    101        hyd  2.0  25.0
None
   employee_id       city  exp   age
0          101        hyd  NaN  25.0
1          102    chennai  4.0  30.0
2          103  bangalore 

In [ ]:
import pandas as pd
data = {
    "Name":["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Mumbai","Chennai","Bengalore","Mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]
}
df=pd.DataFrame(data)
print(df)
df.groupby('City')['Age'].mean()
df.groupby('City')['Salary'].sum()
df.groupby('City')['Age'].agg(['mean', 'max', 'min'])
df.groupby('City')['Salary'].agg(['mean', 'max', 'min'])


     Name  Age       City  Salary
0    Ravi   22  Hyderabad   30000
1   Priya   24    Chennai   40000
2    Arun   21  Bangalore   28000
3   Sneha   25  Hyderabad   50000
4   Kiran   23     Mumbai   35000
5  Anjali   26    Chennai   45000
6  Vikram   20  Bengalore   25000
7   Meena   27     Mumbai   55000


,mean,max,min
City,,,
Bangalore,28000.0,28000,28000
Bengalore,25000.0,25000,25000
Chennai,42500.0,45000,40000
Hyderabad,40000.0,50000,30000
Mumbai,45000.0,55000,35000


In [ ]:
df=pd.DataFrame(data)
print(df)
df.groupby('City').agg({
    'Age' :['mean', 'max'],
    'Salary' : ['sum', 'count']
})

     Name  Age       City  Salary
0    Ravi   22  Hyderabad   30000
1   Priya   24    Chennai   40000
2    Arun   21  Bangalore   28000
3   Sneha   25  Hyderabad   50000
4   Kiran   23     Mumbai   35000
5  Anjali   26    Chennai   45000
6  Vikram   20  Bengalore   25000
7   Meena   27     Mumbai   55000


Age     Salary      
           mean max    sum count
City                            
Bangalore  21.0  21  28000     1
Bengalore  20.0  20  25000     1
Chennai    25.0  26  85000     2
Hyderabad  23.5  25  80000     2
Mumbai     25.0  27  90000     2

In [ ]:
# Merge or joining
 #join () multiple table to combain of sequal
 #join is an operation to combine a common column
 #types of joins
# 1. Inner join( only common tables of columns)
# 2. left join( if common two table is equal of one is first and remaining table is  equal to table is left)
# 3. right join( first we consider a common ,and table is right)
# 4. full join (   )
# methods are (how)

import pandas as pd
df1 = pd.DataFrame({
    'ID' : [1, 2, 3, 4],
    'Name' : ['A', 'B', 'C', 'D']

})
df2 = pd.DataFrame({
    'ID' : [1, 2,3, 5],
    'Salary' : [500, 1000, 2000, 2500]


})
print(df1)
print(df2)


   ID Name
0   1    A
1   2    B
2   3    C
3   4    D
   ID  Salary
0   1     500
1   2    1000
2   3    2000
3   5    2500


In [ ]:
merged = pd.merge(
    df1,df2,on='ID',how='inner'
)
import pandas as pd
df1 = pd.DataFrame({
    'ID' : [1, 2, 3, 4],
    'Name' : ['A', 'B', 'C', 'D']

})
df2 = pd.DataFrame({
    'ID' : [1, 2,3, 5],
    'Salary' : [500, 1000, 2000, 2500]


})
print(df1)
print(df2)
merged = pd.merge(
    df1,df2,on='ID',how='inner'
)
print(merged)
merged = pd.merge(
    df1,df2,on='ID',how='outer'
)
print(merged)
combined = pd.concat(
    [df1,df2],
    axis=0,
    ignore_index=True
)
print(combined)
combined = pd.concat(
    [df1,df2],
    axis=1,
    ignore_index=True
)
print(combined)

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D
   ID  Salary
0   1     500
1   2    1000
2   3    2000
3   5    2500
   ID Name  Salary
0   1    A     500
1   2    B    1000
2   3    C    2000
   ID Name  Salary
0   1    A   500.0
1   2    B  1000.0
2   3    C  2000.0
3   4    D     NaN
4   5  NaN  2500.0
   ID Name  Salary
0   1    A     NaN
1   2    B     NaN
2   3    C     NaN
3   4    D     NaN
4   1  NaN   500.0
5   2  NaN  1000.0
6   3  NaN  2000.0
7   5  NaN  2500.0
   0  1  2     3
0  1  A  1   500
1  2  B  2  1000
2  3  C  3  2000
3  4  D  5  2500


In [ ]:
#read_csv(it is common seperated values)
# pd.read_csv  () ,pd.read_excel, pd.read_json (file name,file path, file extension)


In [ ]:
import pandas as pd


In [ ]:
pd.read_csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/mnist_test.csv',


)
print(df)

      7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665

In [ ]:
import pandas as pd
print(df.head())
print(df.tail())
print(df.len())

   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045   
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10

AttributeError: 'DataFrame' object has no attribute 'len'

In [ ]:
import pandas as pd
df = pd.read_excel('/content/Sample - Superstore.csv.xlsx',

)
print(df)
print(df.head(5))
print(df.tail(3))

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
...      ...             ...        ...        ...             ...   
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class   
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class   

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson 

In [ ]:
# Cleaning Data
# missing (isna,dropna,fillna),incorrect,Duplicate,invalid
#

In [ ]:
# Duplicate Data : it is find process ( df.duplicated)
import pandas as pd
data ={
    "EmpID" :[101,102,103,104,105,106,107,108,109,110,110],
    "Name" : [ "Rama", "PRASHU", "priya", "Ammu", "ANJALI","Vikram", "yamini","meena","RAHUL","Sneha", "Sneha"],
    "City" : ["Hyderabad","Hyderabad", "CHENNAI", "chennai", "Banglore", "BANGLORE","mumbai", "MUMBAI", "Delhi", "Hyderabad","Hyderabad"],
    "Salary" :[ 3000,4000,35000,35000,75000,55000,55000,6000,65000,75000,75000]

}
df = pd.DataFrame(data)
print(df)
df.duplicated()
df.duplicated().sum()


    EmpID    Name       City  Salary
0     101    Rama  Hyderabad    3000
1     102  PRASHU  Hyderabad    4000
2     103   priya    CHENNAI   35000
3     104    Ammu    chennai   35000
4     105  ANJALI   Banglore   75000
5     106  Vikram   BANGLORE   55000
6     107  yamini     mumbai   55000
7     108   meena     MUMBAI    6000
8     109   RAHUL      Delhi   65000
9     110   Sneha  Hyderabad   75000
10    110   Sneha  Hyderabad   75000


np.int64(1)

In [ ]:

df = pd.DataFrame(data)
print(df)
df.duplicated()
duplicates = df[df.duplicated()]
print(df)
print("                            ")
duplicates = df[df.duplicated(keep=False)]
print(duplicates)
print("                      ")
d = df[df.duplicated()]
total = d["Salary"].sum()
print(total)
print("                    ")
d = df[df.duplicated(keep =False)]
total = d["Salary"].sum()
print(total)
print("                      ")




    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500
    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            

KeyError: 'Salary'

In [ ]:
df["City"].duplicated()
duplicates = df[df["EmpID"].duplicated()]
print(duplicates)
#or
df[df["EmpID"].duplicated()]
duplicates = df[df["EmpID"].duplicated(keep=False)]
print(duplicates)
df[df.duplicated(keep=False)]
df[df["Name"].duplicated(keep=False)]


    EmpID   Name       City  Salary
10    110  Sneha  Hyderabad   75000
    EmpID   Name       City  Salary
9     110  Sneha  Hyderabad   75000
10    110  Sneha  Hyderabad   75000


,EmpID,Name,City,Salary
9,110,Sneha,Hyderabad,75000
10,110,Sneha,Hyderabad,75000


In [ ]:
# Drop Duplicates
import pandas as pd
import pandas as pd
data ={
    "EmpID" :[101,102,103,104,105,106,107,108,109,110,110],
    "Name" : [ "Rama", "PRASHU", "priya", "Ammu", "ANJALI","Vikram", "yamini","meena","RAHUL","Sneha", "Sneha"],
    "City" : ["Hyderabad","Hyderabad", "CHENNAI", "chennai", "Banglore", "BANGLORE","mumbai", "MUMBAI", "Delhi", "Hyderabad","Hyderabad"],
    "Salary" :[ 3000,4000,35000,35000,75000,55000,55000,6000,65000,75000,75000]

}
df = pd.DataFrame(data)
print(df)
df.duplicated()
df = df.drop_duplicates(keep= "last")
print(df)
print("                  ")
df =df.drop_duplicates(
    subset=["EmpID"],keep="first")
print("                  ")



    EmpID    Name       City  Salary
0     101    Rama  Hyderabad    3000
1     102  PRASHU  Hyderabad    4000
2     103   priya    CHENNAI   35000
3     104    Ammu    chennai   35000
4     105  ANJALI   Banglore   75000
5     106  Vikram   BANGLORE   55000
6     107  yamini     mumbai   55000
7     108   meena     MUMBAI    6000
8     109   RAHUL      Delhi   65000
9     110   Sneha  Hyderabad   75000
10    110   Sneha  Hyderabad   75000
    EmpID    Name       City  Salary
0     101    Rama  Hyderabad    3000
1     102  PRASHU  Hyderabad    4000
2     103   priya    CHENNAI   35000
3     104    Ammu    chennai   35000
4     105  ANJALI   Banglore   75000
5     106  Vikram   BANGLORE   55000
6     107  yamini     mumbai   55000
7     108   meena     MUMBAI    6000
8     109   RAHUL      Delhi   65000
10    110   Sneha  Hyderabad   75000
                  
                  


In [ ]:
#Dataset 1 – Customer Transactions
#This dataset represents customer purchase transactions.

import pandas as pd

data = {

   "TransactionID": [1001, 1002, 1003, 1004, 1005,

                      1006, 1007, 1008, 1009, 1010, 1010, 1011],

   "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran",

                "Anjali", "Vikram", "Meena", "Rahul", "Sneha",

                "Sneha", "Kiran"],

   "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse",

               "Keyboard", "Monitor", "Laptop", "Mobile", "Headphones",

               "Headphones", "Mouse"],

   "Amount": [55000, 25000, 30000, 5000, 1500,

              2500, 18000, 55000, 22000, 5000,

              5000, 1500]}

df = pd.DataFrame(data)

print(df)
df.duplicated()
df.duplicated().sum()
df.duplicated()
duplicates = df.duplicated()
print(duplicates)
print("                 ")
duplicates = df[df.duplicated(keep = False)]
print(duplicates)


print("                             ")
df[df.duplicated(keep=False)]
df[df["Customer"].duplicated(keep=False)]
print(df)
df.duplicated()
df = df.drop_duplicates(keep= "first")
print(df)
print("                  ")
df = df.drop_duplicates(
   subset=["TransactionID"],
   keep="first")




    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
dtype: bool
                 
    TransactionID Customer     Product  Amount
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
                             
    TransactionID Customer     Product  Amou

In [ ]:
# Inconsistent Data
# it is a using the
# it is using the string methods (title,join.split,strip,upper,lower)
import pandas as pd

data = {

   "TransactionID": [1001, 1002, 1003, 1004, 1005,

                      1006, 1007, 1008, 1009, 1010, 1010, 1011],

   "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran",

                "Anjali", "Vikram", "Meena", "Rahul", "Sneha",

                "Sneha", "Kiran"],

   "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse",

               "Keyboard", "Monitor", "Laptop", "Mobile", "Headphones",

               "Headphones", "Mouse"],

   "Amount": [55000, 25000, 30000, 5000, 1500,

              2500, 18000, 55000, 22000, 5000,

              5000, 1500]}

df = pd.DataFrame(data)

print(df)
df["Customer"] =df["Customer"].str.title()
print(df)
df["Customer"] =df["Customer"].str.lower()
print(df)
df["Customer"] =df["Customer"].str.upper()
print(df)
df["Customer"] =df["Customer"].str.strip()
print(df)
df["product"] =df["Product"].str.lower()
print(df)
df["product"] =df["Product"].str.strip().str.upper()
print(df)
df["Customer"],df["Product"]=df["Customer"].str.strip(),df["Product"].str.title()
print(df)
laptop_data =df[ df["Product"].str.strip().str.lower()=="laptop"]
print(laptop_data)
laptop_data =df[ df["Product"].str.strip().str.lower()=="laptop"]
print(laptop_data)






    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500
    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            

In [ ]:
# Time period Series
import pandas as pd
import pandas as pd
data = {
    "Date": [
        "2025-01-01",
        "2025-01-02",
        "2025-01-03",
        "2025-01-04",
        "2025-01-05",
        "2025-01-06"

    ],
    "Sales": [5000, 6500, 4200, 7000, 5500, 6500]}

df = pd.DataFrame(data)
print(df)
print(df.dtypes)
df["Date"]=pd.to_datetime(df["Date"])
print(df.dtypes)
date = pd.to_datetime("2025-08-22")
print(date)
dates = pd.date_range(
    start="2025-01-01",
    end="2025-01-10"
)
print(dates)
print("               ")
date = pd.date_range(
    start="2025-01-01",
    periods=10
)
print(date)
print("          ")
dates = pd.date_range(start="2025-01-01",periods=50,freq="D")
print(dates)
print("          ")
dates = pd.date_range(start="2025-01-01",periods=12,freq="MS")
print(dates)
print("          ")
dates = pd.date_range(start="2025-01-01",periods=12,freq="ME")
print(dates)
print("                  ")
dates = pd.date_range(start="2025-01-01",periods=365,freq="D")
print(dates)
print("                        ")
dates = pd.date_range(start="2025-01-01",periods=17,freq="YE")
print(dates)
print("                ")
dates = pd.date_range(start="2025-01-01",periods=23,freq="min")
print(dates)
print("                      ")
dates = pd.date_range(start="2025-01-01",periods=23,freq="h")
print(dates)
print("                      ")
dates = pd.date_range(start="2025-01-01",periods=23,freq="s")
print(dates)
print("                      ")



         Date  Sales
0  2025-01-01   5000
1  2025-01-02   6500
2  2025-01-03   4200
3  2025-01-04   7000
4  2025-01-05   5500
5  2025-01-06   6500
Date     object
Sales     int64
dtype: object
Date     datetime64[ns]
Sales             int64
dtype: object
2025-08-22 00:00:00
DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')
               
DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')
          
DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12',
               '2

In [ ]:

# Genetating another method
# numpy
# filtering the data for any in year,hour,day,min,month
#  groupby Aggrigations sum,min,max (high),count(how many),mean,median
# for getting month name ,Day name ,week
import pandas as pd
import numpy as np
date = pd.date_range(start="2025-03-01",periods=30, freq="D")
sales = np.random.randint( 2000,10000,size=30)
df = pd.DataFrame({
    "Date":dates,
    "Sales":sales
})
print(df)
df["Date"] = pd.to_datetime(df["Date"])
print(df)
df["Date"].dt.year
df[df["Date"].dt.year == 2026]

df.groupby(df["Date"].dt.year)["Sales"].mean()
df.groupby(df["Date"].dt.year)["Sales"].max()
df.groupby(df["Date"].dt.year)["Sales"].min()
df.groupby(df["Date"].dt.year)["Sales"].sum()
df.groupby(df["Date"].dt.year)["Sales"].count()
df.groupby(df["Date"].dt.year)["Sales"].median()
df.groupby(df["Date"].dt.year)["Sales"].sum()
df["Date"].dt.month_name()

df["Month"] = df["Date"].dt.month_name()
print(df)
df["Month"] = df["Date"].dt.month_name()
print(df)
df["Day"] = df["Date"].dt.day_name()
print(df)
#for getting the month
df["Date"].dt.month
#for getting some particular month
df[df["Date"].dt.month == 1]
df[df["Date"].dt.month == 2]
#for getting the month with month name
df["Date"].dt.month_name()
#Filtering based on day
df[df["Date"].dt.day == 14]
#for getting the day name
df[df["Date"].dt.day_name()==14]
#for getting the month
df["Date"].dt.month
#for getting some particular month
df[df["Date"].dt.month == 1]
df[df["Date"].dt.month == 2]
#for getting the month with month name
df["Date"].dt.month_name()
#Filtering based on day
df[df["Date"].dt.day == 14]
#for getting the day name
df["Date"].dt.day_name()
#for getting particular day name
df[df["Date"].dt.day_name() == "Sunday"]






         Date  Sales
0  2025-01-01   9811
1  2025-01-02   5770
2  2025-01-03   6242
3  2025-01-04   3372
4  2025-01-05   7057
5  2025-01-06   8801
6  2025-01-07   9624
7  2025-01-08   8293
8  2025-01-09   5817
9  2025-01-10   5438
10 2025-01-11   2145
11 2025-01-12   2619
12 2025-01-13   9791
13 2025-01-14   4864
14 2025-01-15   7537
15 2025-01-16   9086
16 2025-01-17   9749
17 2025-01-18   3987
18 2025-01-19   9324
19 2025-01-20   8356
20 2025-01-21   4519
21 2025-01-22   2547
22 2025-01-23   7617
23 2025-01-24   9066
24 2025-01-25   5441
25 2025-01-26   7004
26 2025-01-27   3353
27 2025-01-28   4733
28 2025-01-29   7604
29 2025-01-30   9442
         Date  Sales
0  2025-01-01   9811
1  2025-01-02   5770
2  2025-01-03   6242
3  2025-01-04   3372
4  2025-01-05   7057
5  2025-01-06   8801
6  2025-01-07   9624
7  2025-01-08   8293
8  2025-01-09   5817
9  2025-01-10   5438
10 2025-01-11   2145
11 2025-01-12   2619
12 2025-01-13   9791
13 2025-01-14   4864
14 2025-01-15   7537
15 2025-01-16

,Date,Sales,Month,Day
4,2025-01-05,7057,January,Sunday
11,2025-01-12,2619,January,Sunday
18,2025-01-19,9324,January,Sunday
25,2025-01-26,7004,January,Sunday


In [ ]:
import numpy as np



In [ ]:
# concatenate()
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
print(arr1,arr2)
result = np.concatenate((arr1,arr2))
print(result.ndim)
print(arr1.shape)
print(arr2.shape)
print("_______________________________")
#============================================
# axis =0 means colums wise concatenadation
#===============2D array ====================
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.concatenate((arr1,arr2),axis =0)
print(result)
print(result.ndim)
print("_________________________________")

#================1D axis = 0 =====================
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.concatenate((arr1,arr2),axis =0)
print(result)
print("_________________________________")

#===============2D array axis =1  ====================
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.concatenate((arr1,arr2),axis =1)
print(result)
print(result.ndim)
print("_________________________________")
#===============1D array axis =1  ====================
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.concatenate((arr1,arr2),axis =1)
print(result)

print("_________________________________")
#========stack axis =0 ============================
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.stack((arr1, arr2),axis= 0)
print(result)
#========stack axis =0 ============================
print("____________________________-")
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.stack((arr1, arr2),axis= 0)
print(result)
print(result.ndim)
#========stack axis =1============================
print("______________________________")
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.stack((arr1, arr2))
print(result)
#========stack axis =1============================
print("_________________________----")
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.stack((arr1, arr2),axis= 1)
print(result)
print(result.ndim)
# v stack () it is vertical stacking
# ============ 1D=================
print("v1d_____________________________--")
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.vstack((arr1, arr2))
print(result)

#============= exceptional case of vstack of 2D============
print("v2d_____________________________")
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.vstack((arr1,arr2))
print(result)
#============= exceptional case of vstack of 3D============
print("v3d_____________________________")
arr1 = np.array([[10,20],[30,4],[80,50]])
arr2 = np.array([[50,60],[70,80],[40,60]])
arr3 = np.array([[100,110],[120,130],[140,150]])
result = np.vstack((arr1,arr2,arr3))
print(result)
# Horizontal stack(hstack)
# ============ hstack of  1D=================
print("h1d_____________________________--")
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.hstack((arr1, arr2))
print(result)
print(result.ndim)

#============= exceptional case of hstack of 2D============
print("h2d_____________________________")
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.hstack((arr1,arr2))
print(result)
print(result.ndim)
#============= exceptional case of hstack of 3D============
print("h3d_____________________________")
arr1 = np.array([[10,20],[30,4],[80,50]])
arr2 = np.array([[50,60],[70,80],[40,60]])
arr3 = np.array([[100,110],[120,130],[140,150]])
result = np.hstack((arr1,arr2,arr3))
print(result)
print(result.ndim)



[10 20 30] [40 50 60]
1
(3,)
(3,)
_______________________________
[[10 20]
 [30  4]
 [50 60]
 [70 80]]
2
_________________________________
[[10 20]
 [30  4]
 [50 60]
 [70 80]]
_________________________________
[[10 20 50 60]
 [30  4 70 80]]
2
_________________________________
[[10 20 50 60]
 [30  4 70 80]]
_________________________________
[[10 20 30]
 [50 60 70]]
____________________________-
[[10 20 30]
 [50 60 70]]
2
______________________________
[[10 20 30]
 [50 60 70]]
_________________________----
[[10 50]
 [20 60]
 [30 70]]
2
v1d_____________________________--
[[10 20 30]
 [50 60 70]]
v2d_____________________________
[[10 20]
 [30  4]
 [50 60]
 [70 80]]
v3d_____________________________
[[ 10  20]
 [ 30   4]
 [ 80  50]
 [ 50  60]
 [ 70  80]
 [ 40  60]
 [100 110]
 [120 130]
 [140 150]]
h1d_____________________________--
[10 20 30 50 60 70]
1
h2d_____________________________
[[10 20 50 60]
 [30  4 70 80]]
2
h3d_____________________________
[[ 10  20  50  60 100 110]
 [ 30   4  70 