<a href="https://colab.research.google.com/github/neerukondaramalakshmi2005-dotcom/Data-Analysis-/blob/main/NUMPY_AS_NP_NOTES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(np.__version__)

2.1.3


In [ ]:
# NUMPY --> IT IS A NUMERICAL PYTHON --> it is using Data scince,DA, ML
# LIST  --> is the Heteogenious
# Array is a not
# np.array(), arr.ndim() it is how many  dimensional  ex : (1,2,3),np.arrange().np.Zeros(),np.
import numpy as np
arr = np.array([10, 20, 30, 40, 50,])
print(arr.ndim)
print(arr)
print("                ")
arr = np.array([[10, 20, 30],[40, 50, 60]])
print(arr.ndim)
print(arr)
print("                  ")
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10 ,11, 12]]])
print(arr.ndim)
print(arr)
# shape
arr.shape
# np.arange()
arr= np.arange(1,10)
print(arr)
#===============================
# np.arange --> it is step method is using the odd numbers(1,10,2)
arr= np.arange(1,10,2)
print(arr)
#=========================
#array of ones:
#==================
print("=================Onces==================")
#1D
ones_1d = np.ones((5))
print("\n1D:")
print(ones_1d)
#2D
ones_2d = np.ones((2,3))
print("\n2D:")
print(ones_2d)
#3D
ones_3d = np.ones((2,2,3))
print("\n3D:")
print(ones_3d)
#================================
# np.Zeros() --> it is all zero
#===============================
print("=================Zeros==================")
#1D
zeros_1d = np.zeros(5)
print("1D:")
print(zeros_1d)
#2D
zeros_2d = np.zeros((2,3))
print("\n2D:")
print(zeros_2d)
#3D
zeros_3d = np.zeros((2,2,3))
print("\n3D:")
print(zeros_3d)
#======================
#3. Arrays of any constant values
#==================================
print("\n=======3.FULL/CONSTANT VALUE==============")
#1D
# 5 is the count , 10 is the number
full_1d = np.full(5,10)
print("1D:")
print(full_1d)
#2D
# 2,3 is the count , 10 is the number
full_2d = np.full((2,3),10)
print("2D:")
print(full_2d)
# 2,3 is the count , 10 is the number
full_3d = np.full((2,2,3),100)
print("3D:")
print(full_3d)
#======================
# RESHAPE()
#===============
print("\n============reshape()===========")
arr = np.arange(1,7)
print(arr)
a=arr.reshape(2,3,1)
print(a)
# a=arr.reshape() two dimensional
arr = np.arange(1,11).reshape(5,2)
print(arr)
# for getting the dtype method
#================= int ====================
print("\n===============int==============")
arr = np.array([10.9, 20.9,3.0, 1],dtype="int")
print(arr)
print(arr.dtype)
#================= float ====================
print("\n===============float==============")
arr = np.array([10.9, 20.9,3.0, 1],dtype="float")
print(arr)
print(arr.dtype)
#================= string ====================
print("\n===============string==============")
arr = np.array(["Rama","Prashu"],dtype="str")
print(arr)
print(arr.dtype)


1
[10 20 30 40 50]
                
2
[[10 20 30]
 [40 50 60]]
                  
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
=================Onces==================

1D:
[1. 1. 1. 1. 1.]

2D:
[[1. 1. 1.]
 [1. 1. 1.]]

3D:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
=================Zeros==================
1D:
[0. 0. 0. 0. 0.]

2D:
[[0. 0. 0.]
 [0. 0. 0.]]

3D:
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

=======3.FULL/CONSTANT VALUE==============
1D:
[10 10 10 10 10]
2D:
[[10 10 10]
 [10 10 10]]
3D:
[[[100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]]]

============reshape()===========
[1 2 3 4 5 6]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

===============int==============
[10 20  3  1]
int64

===============float==============
[10.9 20.9  3.   1. ]
float64

===============string==============
['Rama' 'Prashu']
<U6


In [ ]:

# step(odd num)
arr= np.arange(10,50,5)
print(arr)
# step(even)
arr= np.arange(2,30,2)
print(arr)
# empID
empID = np.arange(1001 ,1020)
print(empID)
# Decreasing method
arr = np.arange(50,1,-1)
print(arr)
#=======================
# Teacher roll number
#=====================
roll_numbers = np.array([101, 102, 103, 104, 105, 106, 107, 108])
print(roll_numbers.ndim)
# shape()
roll_numbers.shape
# rows,colums all values
roll_numbers=np.arange(101,109)
print(roll_numbers)
# rows,columns
roll_numbers=np.arange(2,8)
print(roll_numbers)




[10 15 20 25 30 35 40 45]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019]
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2]
1
[101 102 103 104 105 106 107 108]
[2 3 4 5 6 7]


In [ ]:
import numpy as np
#arr = np.random.random(5) #used to generate random arrays from 0-1 in float format(with decimals)
#arr1 = np.random.random((2,3)) #used to generate random 2D arrays from 0-1 in float format(with decimals)
#arr2 = np.random.random((2,2,3)) ##used to generate random 3D arrays from 0-1 in float format(with decimals)
arr = np.random.uniform(10,50,5) #used to generate random 1D arrays in the specified range in float format
print(arr)
arr2 = np.random.uniform(10,50,(2,3)) #used to generate random 2D arrays in the specified range in float format
print(arr2)
arr3 = np.random.uniform(10,50,(2,2,3)) #used to generate random 3D arrays in the specified range in float format
print(arr3)
arr1 = np.random.randn(5) #used to generate random 1D arrays from -infinity to +infinity
print(arr1)
arr11 = np.random.randn(2,3) #used to generate random 2D arrays from -infinity to +infinity
print(arr11)
arr12 = np.random.randn(5) #used to generate random 3D arrays from -infinity to +infinity
print(arr12)



[44.90217836 23.61119596 14.99505294 36.35848165 40.74470563]
[[13.5722272  31.49048345 43.23597845]
 [25.87903824 17.29890343 27.10695016]]
[[[46.76880573 29.8796855  49.19233561]
  [30.49952665 44.42981742 36.62467806]]

 [[10.29565648 41.3116127  28.72003398]
  [46.07788982 46.1851752  10.83417889]]]
[ 0.90201396 -0.08658859  0.26400826  1.0772816   0.14017869]
[[-1.45454187 -1.21723567 -0.65766508]
 [-0.1881779  -0.50427867  1.02191   ]]
[ 0.08138143  0.49481868  0.82961585 -0.38666824 -1.17509306]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
result = np.random.choice(arr) #used to choose a random value from the array passed(real time of truth and dare)
print(result)
result = np.random.choice(arr, 3) #used to choose a random value from the array a number of specified times
names = ['Ravi', 'Priya', 'Arun', 'Sneha']
result = np.random.choice(names, 3) #will choose from an array of strings as well
print(result)
arr1 = [10,20,30]
result = np.random.choice(arr1, size=5, p=[0.5, 0.2, 0.3]) #used to print the values with probabilities for higher chances of getting a certain value
print(result) #the probability value passed for the values should sum up to 1.
ar = np.random.uniform(10,50,(2,3))
# =================================
np.random.seed(10) #used to freeze the generated random values for the whole code block for the specified number of times(approximately) in runtime
print(ar)
#np.random.shuffle(arr) #used to shuffle values in an array completely, and deleting the original order but keeps the original values
print(arr)
result = np.random.permutation(arr) #also used to shuffle values in an array but stores it in a new variable, therefore keeping the original order as it is
print(result)

roll_numbers= np.array([101, 102, 103, 104, 105, 106, 107, 108])
print(np.random.shuffle(roll_numbers))
employees = np.array(['Ravi', 'Priya', 'Arun', 'Sneha', 'Kiran'])
print(np.random.shuffle(employees))
numbers = ([10,20,30,40,50])
result= np.random.permutation(numbers)
print(result)
arr = np.arange(1,25).reshape(4,6)
print(arr)
arr = np.arange(1,21).reshape(4,5)
print(arr.shape)

50
['Sneha' 'Sneha' 'Arun']
[30 10 10 30 30]
[[31.63523725 15.2583261  26.54669498]
 [41.14915233 33.35605463 17.30525745]]
[10 20 30 40 50]
[30 40 10 50 20]
None
None
[20 40 50 30 10]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
(5, 2)


In [ ]:
import numpy as np
#Question 2
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((3,4))
zeros_3d = np.zeros((2,3,4))
print(zeros_1d)
print(zeros_2d)
print(zeros_3d)
#Question 3
ones_1d = np.ones(5)
ones_2d = np.ones((2,3))
ones_3d = np.ones((2,2,3))
print(ones_1d)
print(ones_2d)
print(ones_3d)
#Question 4
arr = np.full((4, 5), 1000)
print(arr, arr.shape, arr.ndim, arr.dtype)
#Question 5
matrix_eye = np.eye(5)
print(matrix_eye)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]] (4, 5) 2 int64
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
arr=np.linspace(0,100,10)
print(arr)
import numpy as np
arr=np.linspace(1,50,15)
print(arr)
arr=np.array([10,20,30,40,50,60,70])
print(arr)
print(arr[0])
print(arr[-1:])
print(arr[3])
print(arr[5])
arr=np.array([10,20,30,40,50,60,70,80])
print(arr)
print(arr[0:4])
print(arr[2:5])
print(arr[-3:])
print(arr[::2])#to print alternative number
print(arr[0:7:2])#to print alternative number
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
print(arr[1,1])
print(arr[0,2])
print(arr[2,0])
print(arr[0])

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[ 1.   4.5  8.  11.5 15.  18.5 22.  25.5 29.  32.5 36.  39.5 43.  46.5
 50. ]
[10 20 30 40 50 60 70]
10
[70]
40
60
[10 20 30 40 50 60 70 80]
[10 20 30 40]
[30 40 50]
[60 70 80]
[10 30 50 70]
[10 30 50 70]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
50
30
70
[10 20 30]


In [ ]:
# Aggcal :- it is mathemitaical or statical
#SUM,MIN,MAX,ME
import numpy as np
#============ sum 1D ================
arr = np.array([10,20,40,30,50])
print(np.sum(arr))
#=============sum 2D =================
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.sum(arr))
# ============ row wise sum 2D ================
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.sum(arr,axis=0))
# ============ row wise sum 2D ================
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.sum(arr,axis=1))
#============ min 1D ================
arr = np.array([10,20,40,30,50])
print(np.min(arr))
# ==============min 2D==============
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.min(arr))
#============ max 1D ================
arr = np.array([10,20,40,30,50])
print(np.max(arr))
#============ max 2D===================
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.max(arr))
#============mean 1D====================
arr = np.array([10,20,40,30,50])
print(np.mean(arr))
#============ mean 2D===================( sum of values and number of values)
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.mean(arr))
#============std 1D====================( over all  differ from the mean)
arr = np.array([10,20,40,30,50])
print(np.std(arr))
#============ std 2D===================
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.std(arr))
#============var 1D====================( it is varience) spread out of mean
arr = np.array([10,20,40,30,50])
print(np.var(arr))
#============ var 2D===================Low variance → values are close together
#                                     High variance → values are widely spread

arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.var(arr))
# ================percentile 1D ()==========(below which a certain percentage of observations fall.)
# it is only for the (1 to 100) The 50th percentile is the median.
#25th percentile → Q1
#50th percentile → Median
#75th percentile → Q3

arr = np.array([10,20,40,30,50])
print(np.percentile(arr,30))
#=============== percentile 2D========================
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.percentile(arr,100))

# percentail and quantail ( both are vise versa)
#percentile → percentage → 0–100
#quantile    → proportion → 0–1

# ================== quantile ====================( it only taken for 0 to 1 values only)
arr = np.array([10,20,30,40,50,80])
print(np.percentile(arr,25))
print(np.quantile(arr,0.25))
#============= argmax()======================( it is index position of the largest value
arr = np.array([10,20,40,30,50])
print(np.argmax(arr))
#============ argmax() 2D===================
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.argmax(arr))
#============= argmin()======================
arr = np.array([10,20,40,30,50])
print(np.argmin(arr))
#============ argmin() 2D===================
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
# =================log10===================
arr = np.array([10,20,40,30,50])
print(np.log10(arr))
# =================log10===================
arr = np.array([10,100,1000,100000])
print(np.log10(arr))
print("_________________________________- ")
print(np.log2(arr))


# ==============log10 2D==============
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.log10(arr))
print(" ______________________________  ")
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.log(2))
print(np.log10(arr))
print(np.log(3))
#===================== Round()===================( it is only 5 values=)
arr = np.array([10.555, 20.786,30.676]) # ( it is only taken for Decimal values like 10.20 taken the value of 10)
print(np.round(arr,2))
# ==================floor=================( it include the lower value only)
arr = np.array([10.2, 20.4,30.5])
print(np.floor(arr))
# ================== ceil===================( it is upper value only) like we 10.2 = 11.)
arr = np.array([10.2, 20.3, 30.4, 50.4])
print(np.ceil(arr))
#=================== abs() absoult method it is used to negetaive also convert the positive value
# abs is making into positive
arr = np.array([-10, -4, -70,0,8,90])
print(np.abs(arr))
#================= sort()=============== (it is descending [::-1] order to change)
arr = np.array([50,40,60,20,60])
result = np.sort(arr)[::-1]
print(result)
#================sort()=====================
arr = np.array([10,20,40,30,50])
print(np.sort(arr))

150
210
[ 40  70 100]
[ 70 140]
10
10
50
60
30.0
35.0
14.142135623730951
17.07825127659933
200.0
291.6666666666667
22.0
60.0
22.5
22.5
4
5
0
[1.         1.30103    1.60205999 1.47712125 1.69897   ]
[1. 2. 3. 5.]
_________________________________- 
[ 3.32192809  6.64385619  9.96578428 16.60964047]
[[1.         1.30103    1.60205999]
 [1.47712125 1.69897    1.77815125]]
 ______________________________  
0.6931471805599453
[[1.         1.30103    1.60205999]
 [1.47712125 1.69897    1.77815125]]
1.0986122886681098
[10.56 20.79 30.68]
[10. 20. 30.]
[11. 21. 31. 51.]
[10  4 70  0  8 90]
[60 60 50 40 20]
[10 20 30 40 50]


In [ ]:
# concatenate() combining  multiple arrays and to or more arrays  to result would be same dimension
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
print(arr1,arr2)
result = np.concatenate((arr1,arr2))
print(result.ndim)
print(arr1.shape)
print(arr2.shape)
print("_______________________________")
#============================================
# axis =0 means colums wise concatenadation
#===============2D array ====================
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.concatenate((arr1,arr2),axis =0)
print(result)
print(result.ndim)
print("_________________________________")

#================1D axis = 0 =====================
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.concatenate((arr1,arr2),axis =0)
print(result)
print("_________________________________")

#===============2D array axis =1  ====================
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.concatenate((arr1,arr2),axis =1)
print(result)
print(result.ndim)
print("_________________________________")
#===============1D array axis =1  ====================
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.concatenate((arr1,arr2),axis =1)
print(result)

print("_________________________________")
#========stack axis =0 ============================
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.stack((arr1, arr2),axis= 0)
print(result)
#========stack axis =0 ============================
print("____________________________-")
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.stack((arr1, arr2),axis= 0)
print(result)
print(result.ndim)
#========stack axis =1============================
print("______________________________")
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.stack((arr1, arr2))
print(result)
#========stack axis =1============================
print("_________________________----")
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.stack((arr1, arr2),axis= 1)
print(result)
print(result.ndim)
# v stack () it is vertical stacking (high and down)
# ============ 1D=================
print("v1d_____________________________--")
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.vstack((arr1, arr2))
print(result)

#============= exceptional case of vstack of 2D============
print("v2d_____________________________")
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.vstack((arr1,arr2))
print(result)
#============= exceptional case of vstack of 3D============
print("v3d_____________________________")
arr1 = np.array([[10,20],[30,4],[80,50]])
arr2 = np.array([[50,60],[70,80],[40,60]])
arr3 = np.array([[100,110],[120,130],[140,150]])
result = np.vstack((arr1,arr2,arr3))
print(result)
# Horizontal stack(hstack) it is side by side
# ============ hstack of  1D=================
print("h1d_____________________________--")
arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])
result = np.hstack((arr1, arr2))
print(result)
print(result.ndim)

#============= exceptional case of hstack of 2D============
print("h2d_____________________________")
arr1 = np.array([[10,20],[30,4]])
arr2 = np.array([[50,60],[70,80]])
result = np.hstack((arr1,arr2))
print(result)
print(result.ndim)
#============= exceptional case of hstack of 3D============
print("h3d_____________________________")
arr1 = np.array([[10,20],[30,4],[80,50]])
arr2 = np.array([[50,60],[70,80],[40,60]])
arr3 = np.array([[100,110],[120,130],[140,150]])
result = np.hstack((arr1,arr2,arr3))
print(result)
print(result.ndim)



[10 20 30] [40 50 60]
1
(3,)
(3,)
_______________________________
[[10 20]
 [30  4]
 [50 60]
 [70 80]]
2
_________________________________
[[10 20]
 [30  4]
 [50 60]
 [70 80]]
_________________________________
[[10 20 50 60]
 [30  4 70 80]]
2
_________________________________
[[10 20 50 60]
 [30  4 70 80]]
_________________________________
[[10 20 30]
 [50 60 70]]
____________________________-
[[10 20 30]
 [50 60 70]]
2
______________________________
[[10 20 30]
 [50 60 70]]
_________________________----
[[10 50]
 [20 60]
 [30 70]]
2
v1d_____________________________--
[[10 20 30]
 [50 60 70]]
v2d_____________________________
[[10 20]
 [30  4]
 [50 60]
 [70 80]]
v3d_____________________________
[[ 10  20]
 [ 30   4]
 [ 80  50]
 [ 50  60]
 [ 70  80]
 [ 40  60]
 [100 110]
 [120 130]
 [140 150]]
h1d_____________________________--
[10 20 30 50 60 70]
1
h2d_____________________________
[[10 20 50 60]
 [30  4 70 80]]
2
h3d_____________________________
[[ 10  20  50  60 100 110]
 [ 30   4  70 

In [6]:
# 11. split 1D,2D,3D array( separation or dividing) equal parts of spliting, value count is equal .
# 2nd method customize  partienising .
import numpy as np
# ================ split  1D array =================
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,3)
print(result)
print("\n_____________________________----")
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,[2,4])
print(result)
print("\n___________________________________---")
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,[0,1,3,6])
print(result)
print("\n___________________________________---")
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,6)
print(result)
print("======================\n2D========================")


[array([10, 20]), array([30, 40]), array([50, 60])]

_____________________________----
[array([10, 20]), array([30, 40]), array([50, 60])]

___________________________________---
[array([], dtype=int64), array([10]), array([20, 30]), array([40, 50, 60]), array([], dtype=int64)]

___________________________________---
[array([10]), array([20]), array([30]), array([40]), array([50]), array([60])]
2D========================


In [16]:
#2D ,3D array
import numpy as np
# ============== 2D array axis = 0 ==================
arr = np.array([[10,20],[30,40],[40,50],[60,80]])
result = np.split(arr,2,axis=0)
print(result)
# ============== 2D array axis = 1 ==================
arr = np.array([[10,20],[30,40],[40,50],[60,80]])
result = np.split(arr,2,axis=1)
print(result)
# ============== 3D array axis = 0 ==================
arr = np.array([[10,20,30],[30,40,50],[40,50,70],[60,80,90]])
result = np.split(arr,2,axis=0)
print(result)
# ============== 3D array axis = 1 ==================( customized index)
arr = np.array([[10,20,40],[30,40,70],[40,50,80],[60,80,90]])
result = np.split(arr,[1,3] ,axis=1)
print(result)
# ============== 3D array axis = 1 ==================( customized index)
arr = np.array([[10,20,40],[30,40,70],[40,50,80],[60,80,90]])
result = np.split(arr,[1,4] ,axis=1)
print(result)



[array([[10, 20],
       [30, 40]]), array([[40, 50],
       [60, 80]])]
[array([[10],
       [30],
       [40],
       [60]]), array([[20],
       [40],
       [50],
       [80]])]
[array([[10, 20, 30],
       [30, 40, 50]]), array([[40, 50, 70],
       [60, 80, 90]])]
[array([[10],
       [30],
       [40],
       [60]]), array([[20, 40],
       [40, 70],
       [50, 80],
       [80, 90]]), array([], shape=(4, 0), dtype=int64)]
[array([[10],
       [30],
       [40],
       [60]]), array([[20, 40],
       [40, 70],
       [50, 80],
       [80, 90]]), array([], shape=(4, 0), dtype=int64)]
