<a href="https://colab.research.google.com/github/neerukondaramalakshmi2005-dotcom/Data-Analysis-/blob/main/numpy_exam_for_20_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)
# a=arr.reshape() two dimensional
arr = np.arange(1,11).reshape(5,2)
print(arr)

[10 20 30 40 50]
1
(5,)
int64
5
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:

#2
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
arr1 = np.array([[7,8,9],[10,11,12]])
print(arr.ndim)
print(arr,arr1)
print("                  ")
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6],[7,8,9],[10,11,12]])
print(arr.ndim)
print(arr)
print("                  ")

2
[[1 2 3]
 [4 5 6]] [[ 7  8  9]
 [10 11 12]]
                  
2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
                  


In [ ]:

#4
ones_1d = np.zeros((5))
print("\n1D:")
print(ones_1d)
#2D
ones_2d = np.zeros((2,3))
print("\n2D:")
print(ones_2d)
#3D
ones_3d = np.zeros((2,2,3))
print("\n3D:")
print(ones_3d)


1D:
[0. 0. 0. 0. 0.]

2D:
[[0. 0. 0.]
 [0. 0. 0.]]

3D:
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:

#10
arr = np.random.uniform(10,50,5)
print(arr)

[45.20615078 12.93509238 35.29360427 22.52205574 20.20122961]


In [ ]:

#9
colours = (["Red","Blue","Green","Yellow", "Black"])
print(colours)
result = np.random.choice(colours, 3)
print(result)

['Red', 'Blue', 'Green', 'Yellow', 'Black']
['Black' 'Green' 'Red']


In [ ]:
#10
arr = ([10,20,30,40,50])
np.random.seed(10)
print(arr)


[10, 20, 30, 40, 50]


In [ ]:

# 11
arr = np.array([5,50,5])
result =np.arange(5,50,5)
print(result)

[ 5 10 15 20 25 30 35 40 45]


In [ ]:
#12
import numpy as np
arr = np.array([10,20,30,40,50,60])
np.random.shuffle(arr)
print(arr)
result = np.random.permutation(arr)
print(result)


[30 10 60 20 50 40]
[20 50 30 60 10 40]


In [ ]:

# 13
arr = np.array([10,20,40,30,50,60]).reshape(2,3)
print(np.percentile(arr,100))


60.0


In [ ]:
#12
np.random.shuffle(arr)
print(arr)
result = np.random.permutation(arr)
print(result)

[10 20 30 40 50 60]
[30 60 10 40 50 20]


In [ ]:

# 14
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(1,12)
print(arr)
print(arr.ndim)


[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
2


In [ ]:
# 15
arr = np.array([[1,2,3],[4,5,6]]).reshape(2,3)
print(arr)
print(arr.ndim)



[[1 2 3]
 [4 5 6]]
2


In [ ]:
arr = np.array([45,56,67,72,81,90,95])
print(np.percentile(arr,100))
print(np.percentile(arr,75))
print(np.quantile(arr,1))



95.0
85.5
95


In [1]:
import numpy as np

# ============================================================
# NUMPY PRACTICE PROGRAM - 20 QUESTIONS
# ============================================================

# 1. 1D Array - dimensions, shape, size, data type
print("\n1. 1D Array")
arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)


# 2. Create 2D and 3D arrays
print("\n2. 2D and 3D Arrays")

arr2 = np.arange(1, 13).reshape(3, 4)
print("2D Array:")
print(arr2)

arr3 = np.arange(1, 25).reshape(2, 3, 4)
print("3D Array:")
print(arr3)


# 3. 1D, 2D and 3D arrays containing zeros
print("\n3. Zero Arrays")

zero_1d = np.zeros(5)
zero_2d = np.zeros((2, 3))
zero_3d = np.zeros((2, 3, 4))

print("1D:")
print(zero_1d)

print("2D:")
print(zero_2d)

print("3D:")
print(zero_3d)


# 4. 2 x 3 array containing ones
print("\n4. Ones Array")

ones = np.ones((2, 3))

print(ones)
print("Dimensions:", ones.ndim)
print("Shape:", ones.shape)


# 5. 3 x 4 array of 7s and identity matrix
print("\n5. Full Array and Identity Matrix")

sevens = np.full((3, 4), 7)
print("3 x 4 Array of 7:")
print(sevens)

identity = np.eye(4)
print("4 x 4 Identity Matrix:")
print(identity)


# 6. Random decimal values between 0 and 1
print("\n6. Random Values")

random_5 = np.random.rand(5)
print("Five random values:")
print(random_5)

random_2x3 = np.random.rand(2, 3)
print("2 x 3 random array:")
print(random_2x3)


# 7. 3 x 3 random values between 10 and 50
print("\n7. Random Values Between 10 and 50")

random_values = np.random.uniform(10, 50, (3, 3))
print(random_values)


# 8. 2 x 4 standard normal distribution
print("\n8. Standard Normal Distribution")

normal = np.random.randn(2, 4)
print(normal)


# 9. Randomly select 3 colors
print("\n9. Random Color Selection")

colors = ["Red", "Blue", "Green", "Yellow", "Black"]

selected = np.random.choice(colors, 3, replace=False)

print("Selected Colors:")
print(selected)


# 10. Fixed random seed
print("\n10. Random Seed")

np.random.seed(10)
first_set = np.random.rand(5)

np.random.seed(10)
second_set = np.random.rand(5)

print("First Set:")
print(first_set)

print("Second Set:")
print(second_set)

print("Both sets are identical:", np.array_equal(first_set, second_set))


# 11. Numbers from 5 to 50 with step 5
print("\n11. Numbers from 5 to 50")

arr = np.arange(5, 51, 5)

print(arr)


# 12. Randomly reorder array
print("\n12. Random Reordering")

arr = np.array([10, 20, 30, 40, 50, 60])

# Change original array
original_changed = arr.copy()
np.random.shuffle(original_changed)

print("Original Array:")
print(arr)

print("Shuffled Array:")
print(original_changed)

# Random reordered copy
random_copy = np.random.permutation(arr)

print("Original remains unchanged:")
print(arr)

print("Random Copy:")
print(random_copy)


# 13. Six equally spaced values from 0 to 100
print("\n13. Equally Spaced Values")

arr = np.linspace(0, 100, 6)

print(arr)


# 14. Reshape and flatten
print("\n14. Reshape and Flatten")

arr = np.array([1, 2, 3, 4, 5, 6,
                7, 8, 9, 10, 11, 12])

matrix = arr.reshape(3, 4)

print("3 x 4 Matrix:")
print(matrix)

one_d = matrix.flatten()

print("1D Array:")
print(one_d)


# 15. Transpose and 3D array
print("\n15. Transpose and 3D Array")

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:")
print(arr)

print("Transpose:")
print(arr.T)

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]]])

print("3D Array:")
print(arr_3d)

print("3D Shape:", arr_3d.shape)


# 16. Data type and conversion to float
print("\n16. Data Type Conversion")

arr = np.array([10, 20, 30, 40, 50])

print("Original Data Type:", arr.dtype)

float_arr = arr.astype(float)

print("Float Array:")
print(float_arr)

print("New Data Type:", float_arr.dtype)


# 17. Indexing, slicing and updating
print("\n17. Indexing and Slicing")

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Retrieve 50
print("50:", arr[1, 1])

# Retrieve last row
print("Last Row:", arr[-1])

# Retrieve first two columns
print("First Two Columns:")
print(arr[:, :2])

# Change 80 to 800
arr[2, 1] = 800

print("After changing 80 to 800:")
print(arr)


# 18. Insert, delete and mathematical analysis
print("\n18. Insert, Delete and Analysis")

arr = np.array([10, 20, 30, 40, 50])

# Add 25 between 20 and 30
arr = np.insert(arr, 2, 25)

print("After inserting 25:")
print(arr)

# Remove 40
arr = np.delete(arr, 3)

print("After deleting 40:")
print(arr)

print("Total:", np.sum(arr))
print("Smallest:", np.min(arr))
print("Largest:", np.max(arr))
print("Average:", np.mean(arr))


# 19. Statistical analysis
print("\n19. Statistical Analysis")

marks = np.array([45, 56, 67, 72, 81, 90, 95])

print("Marks:", marks)

print("Variance:", np.var(marks))
print("Standard Deviation:", np.std(marks))
print("25th Percentile:", np.percentile(marks, 25))
print("75th Percentile:", np.percentile(marks, 75))

print("Position of Highest Mark:", np.argmax(marks))
print("Position of Lowest Mark:", np.argmin(marks))

print("Base-10 Logarithm:")
print(np.log10(marks))


# 20. Combining, stacking and splitting
print("\n20. Combining Arrays")

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.array([7, 8, 9])

# Combine A and B into one continuous array
continuous = np.concatenate((A, B))

print("A and B Combined:")
print(continuous)

# Arrange A and B one below the other
vertical = np.vstack((A, B))

print("A and B Vertically:")
print(vertical)

# Arrange A and B along a newly created dimension
stacked = np.stack((A, B))

print("A and B using Stack:")
print(stacked)

# Combine all three vertically
vertical_all = np.vstack((A, B, C))

print("All Three Vertically:")
print(vertical_all)

# Combine all three horizontally
horizontal_all = np.hstack((A, B, C))

print("All Three Horizontally:")
print(horizontal_all)

# Divide combined 1D array into 3 equal parts
parts = np.split(horizontal_all, 3)

print("Three Equal Parts:")
print(parts)

print("\n==============================")
print("ALL 20 QUESTIONS COMPLETED")
print("==============================")


1. 1D Array
Array: [10 20 30 40 50]
Dimensions: 1
Shape: (5,)
Size: 5
Data Type: int64

2. 2D and 3D Arrays
2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

3. Zero Arrays
1D:
[0. 0. 0. 0. 0.]
2D:
[[0. 0. 0.]
 [0. 0. 0.]]
3D:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

4. Ones Array
[[1. 1. 1.]
 [1. 1. 1.]]
Dimensions: 2
Shape: (2, 3)

5. Full Array and Identity Matrix
3 x 4 Array of 7:
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
4 x 4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

6. Random Values
Five random values:
[0.79593015 0.21536841 0.76382574 0.69524488 0.83792402]
2 x 3 random array:
[[0.90860124 0.87577715 0.0302817 ]
 [0.50751693 0.8797111  0.75678278]]

7. Random Values Between 10 and 50
[[18.70578138 23.41928617 34.35427927]
 [27.60253647 35.41877132 49.10018177]
 [32.60849334 